# Generated by Django 5.1 on 2024-08-12 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('relationship_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='librarian',
            old_name='Library',
            new_name='library',
        ),
    ]
